name: Scrapy Scheduled Job

# on:
#   schedule:
#     - cron: '0 0 * * *'

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'
      
      - name: Install Scrapy                               
        run: pip install scrapy  

      - name: Run totalspider
        run: scrapy crawl totalspider

