name: Scrapy Run Job

# on:
#   schedule:
#     - cron: '0 0 * * *'

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'
      
      - name: Install Dependencies                               
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip libxml2-dev libxslt1-dev libffi-dev libssl-dev

      - name: Install Scrapy and Scrapy-Splash
        run: |
          pip install scrapy scrapy-splash

      - name: Start Splash
        run: docker run -d -p 8050:8050 -e "SPLASH_TIMEOUT=3600" scrapinghub/splash > splash_logs.txt

      - name: Run totalspider
        run: scrapy crawl totalspider
      
      - name: Upload Splash logs
        uses: actions/upload-artifact@v2
        with:
          name: splash-logs
          path: splash_logs.txt