name: Run Scrapy Spider with Splash

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t scrapy-splash .
      working-directory: .

    - name: Run Docker container
      run: docker run -d --name scrapy-container scrapy-splash

    - name: Check container status
      run: docker ps -a

    - name: Wait for Splash to start
      run: sleep 5

    - name: Run Scrapy spider
      run: docker exec scrapy-splash scrapy crawl totalspider || docker logs scrapy-container