name: Run Scrapy Spider with Splash

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      splash:
        image: scrapinghub/splash
        ports:
          - 8050:8050
        options: --name splash-container

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start Scrapy and Splash containers
      run: docker-compose up -d

    - name: Check container status
      run: docker ps -a

    - name: Wait for containers to start
      run: sleep 10  # Adjust sleep time based on your system's performance and startup times